# Generated by Django 5.1.4 on 2025-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_admin_annotators'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotators',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
