# Generated by Django 5.1.4 on 2025-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_admin_last_login_annotators_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotators',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
