# Generated by Django 5.1.4 on 2025-01-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_annotators_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotators',
            name='is_active',
        ),
    ]
