# Generated by Django 5.1.4 on 2025-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_annotators_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotators',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
