# Generated by Django 5.0.2 on 2025-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_annotators_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotators',
            name='shortcuts',
            field=models.JSONField(default=dict),
        ),
    ]
