# Generated by Django 5.0.2 on 2025-02-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_annotators_shortcuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotators',
            name='shortcuts',
        ),
    ]
