# Generated by Django 5.1.4 on 2025-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_remove_annotators_shortcuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmanager',
            name='tags_med',
            field=models.JSONField(default=list),
        ),
    ]
