# Generated by Django 5.1.4 on 2025-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_tagmanager_tags_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmanager',
            name='tags',
            field=models.JSONField(default=['O']),
        ),
        migrations.AlterField(
            model_name='tagmanager',
            name='tags_med',
            field=models.JSONField(default=['O']),
        ),
    ]
