# Generated by Django 5.1.4 on 2025-03-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_alter_tagmanager_tags_alter_tagmanager_tags_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotators',
            name='financial_tagged_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotators',
            name='general_tagged_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotators',
            name='medical_tagged_count',
            field=models.IntegerField(default=0),
        ),
    ]
