# Generated by Django 5.0.2 on 2025-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_annotators_financial_tagged_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmanager',
            name='tags_fin',
            field=models.JSONField(default=list),
        ),
    ]
