# Generated by Django 5.2 on 2025-06-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_tagmanager_tags_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validators',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('general_validated_count', models.IntegerField(default=0)),
                ('medical_validated_count', models.IntegerField(default=0)),
                ('financial_validated_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validators',
            },
        ),
    ]
