# Generated by Django 5.2 on 2025-06-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_validators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validators',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='validators',
            name='financial_validated_count',
        ),
        migrations.RemoveField(
            model_name='validators',
            name='general_validated_count',
        ),
        migrations.RemoveField(
            model_name='validators',
            name='medical_validated_count',
        ),
    ]
