# Generated by Django 5.2 on 2025-06-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0015_remove_validators_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validators',
            name='email',
        ),
    ]
